### ISSUE TITLE
Set up Kanban Board for Recipe App Project

### ISSUE THREAD

**Issue by zunairkhan811** [zunairkhan811/food-recipe#19]
- We are a team of Two Persons
   - One is Muhammad Zunair khan(@zunairkhan811 )
   - Other Is Lawmsangi (@Lawmsangi )
- Made Kanban Board according to Project Requirements and assigned tasks equally among each other.
- Here is a link to Our Recipe App Project: [Click here](https://github.com/users/zunairkhan811/projects/4/views/1)

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @zunairkhan811 and @Lawmsangi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Your project cannot be accessed.

![image](https://github.com/zunairkhan811/food-recipe/assets/36542986/4290f06d-c46e-4fe2-a4a2-c036e4ac24b0)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by skyv26** [comment]
## Hi @zunairkhan811 and @Lawmsangi, 

Your project is complete!  There is nothing else to say other than... it's time to start your project :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTFhYWM3ODY5MjAyNDJkMTRjYjkwOTc1YzFmZDZhMGIwMDUyM2ZjNiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/xT1XGT9ersCCKjhVny/giphy.gif)

## Highlights
- Good **Issue** title ✅ 
- Descriptive *Issue* description ✅ 


## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zunairkhan811** [comment]
The task is completed here in this [link](https://github.com/users/zunairkhan811/projects/4/views/1). So closing this issue.
